
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kwan Jun Wei
 * @author calvinlim
 */
public class jAdmin extends javax.swing.JFrame {
    private String role="";
    private String username;
    private String password;
    private String address;
    private String postcode;
    private String city;
    private String state;
    private cAdmin admin = new cAdmin();
    /**
     * Creates new form jDashboard
     */
    
    public jAdmin() {
        initComponents(); 
        loadRoles();
    }
    
    public void setRole(String role){
        this.role = role;
    }
    
    public void setUsername(String username){
        this.username = username;
    }
    
    private void loadRoles() {
        // Create the cAdmin object
        cAdmin admin = new cAdmin();

        // Get the distinct roles from cAdmin
        String[] roles = admin.getDistinctRoles();

        // Set the model with the roles array
        comboAdminSearchRole.setModel(new javax.swing.DefaultComboBoxModel<>(roles));
        comboAdminSearchRole.insertItemAt("All", 0);

        // Set the initial selection to "All"
        comboAdminSearchRole.setSelectedIndex(0);

        // Clear the table
        DefaultTableModel model = (DefaultTableModel) tableAdminUser1.getModel();
        model.setRowCount(0);

        // Add user info to the table based on selected role      
        comboAdminSearchRole.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedRole = (String) comboAdminSearchRole.getSelectedItem();
                    DefaultTableModel model = (DefaultTableModel) tableAdminUser1.getModel();
                    model.setRowCount(0);

                    // Get user info from cAdmin
                    List<String[]> userInfoList = admin.getUserInfoList();

                    // Add user info to the table based on selected role
                    for (String[] userInfo : userInfoList) {
                        String role = userInfo[0];
                        String username = userInfo[1];
                        if (selectedRole.equals("All") || selectedRole.equals(role)) {
                            model.addRow(new Object[]{role, username});
                        }
                    }
                            
                }
            }
        });    
    }

 
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        panelRole = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        comboAdminSearchRole = new javax.swing.JComboBox<>();
        txtAdminSearch = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableAdminUser1 = new javax.swing.JTable();
        txtAdminPassword = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtAdminPassword2 = new javax.swing.JPasswordField();
        btnAdminSave = new javax.swing.JButton();
        btnAdminClear = new javax.swing.JButton();
        btnAdminDelete = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        comboAdminRole = new javax.swing.JComboBox<>();
        txtAdminUsername = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        panelProduct = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdminProduct = new javax.swing.JTable();
        comboAdminProductCategory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAdminProductSearch = new javax.swing.JTextField();
        btnAdminShopDeleteProduct = new javax.swing.JButton();
        lblShopPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAdminShopAddProduct = new javax.swing.JButton();
        txtAdminProductAddProductStock = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAdminProductAddProductPrice = new javax.swing.JTextField();
        txtAdminProductAddProductName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        comboAdminProductCategory2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        comboAdminProductCategory1 = new javax.swing.JComboBox<>();
        btnAdminProductAddCategory = new javax.swing.JButton();
        panelHistory = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePurchaseHistory = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnPurchaseHistoryRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboAdminStatusAssignOrder = new javax.swing.JComboBox<>();
        comboAdminStatusAssignDelivery = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboAdminStatusDate = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtAdminStatusSearch = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        comboAdminStatusID = new javax.swing.JComboBox<>();
        comboAdminStatusStatus = new javax.swing.JComboBox<>();
        comboAdminStatusDelivery = new javax.swing.JComboBox<>();
        btnAdminStatusAssign = new javax.swing.JButton();
        panelCustomer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        label123 = new javax.swing.JLabel();
        btnCartRefreshTable = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblCartPrice = new javax.swing.JLabel();
        lblCartTotalItem = new javax.swing.JLabel();
        lblCartItemName = new javax.swing.JLabel();
        txtAdminCustomerAddress = new javax.swing.JTextField();
        txtAdminCustomerCity = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtAdminCustomerName = new javax.swing.JTextField();
        txtAdminCustomerState = new javax.swing.JTextField();
        txtAdminCustomerPostcode = new javax.swing.JTextField();
        txtAdminCustomerSearch = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        btnAdminCustomerSave = new javax.swing.JButton();
        btnAdminCustomerDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Filter By");

        comboAdminSearchRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        comboAdminSearchRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminSearchRoleActionPerformed(evt);
            }
        });

        txtAdminSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminSearchKeyPressed(evt);
            }
        });

        tableAdminUser1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Role", "Username"
            }
        ));
        jScrollPane6.setViewportView(tableAdminUser1);

        jLabel25.setText("Password: ");

        jLabel27.setText("Username: ");

        jLabel28.setText("Confirm Password: ");

        btnAdminSave.setText("Save");
        btnAdminSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSaveActionPerformed(evt);
            }
        });

        btnAdminClear.setText("Clear");
        btnAdminClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminClearActionPerformed(evt);
            }
        });

        btnAdminDelete.setText("Delete");
        btnAdminDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDeleteActionPerformed(evt);
            }
        });

        jLabel30.setText("Contact Number: ");

        comboAdminRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "delivery", "customer", " " }));
        comboAdminRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminRoleActionPerformed(evt);
            }
        });

        jLabel15.setText("Search:");

        javax.swing.GroupLayout panelRoleLayout = new javax.swing.GroupLayout(panelRole);
        panelRole.setLayout(panelRoleLayout);
        panelRoleLayout.setHorizontalGroup(
            panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28))
                .addGap(37, 37, 37)
                .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRoleLayout.createSequentialGroup()
                        .addComponent(btnAdminSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAdminPassword)
                    .addComponent(txtAdminPassword2)
                    .addComponent(comboAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(panelRoleLayout.createSequentialGroup()
                .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRoleLayout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(comboAdminSearchRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRoleLayout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoleLayout.setVerticalGroup(
            panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoleLayout.createSequentialGroup()
                .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRoleLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtAdminPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(comboAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminSave)
                            .addComponent(btnAdminClear)))
                    .addGroup(panelRoleLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(comboAdminSearchRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAdminDelete)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panel.addTab("User Management", panelRole);

        tableAdminProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category Name", "Item Name", "Price", "Stock Left"
            }
        ));
        jScrollPane1.setViewportView(tableAdminProduct);
        if (tableAdminProduct.getColumnModel().getColumnCount() > 0) {
            tableAdminProduct.getColumnModel().getColumn(2).setMaxWidth(300);
            tableAdminProduct.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        comboAdminProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminProductCategoryActionPerformed(evt);
            }
        });

        jLabel2.setText("Category");

        txtAdminProductSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminProductSearchKeyPressed(evt);
            }
        });

        btnAdminShopDeleteProduct.setText("Delete Item");
        btnAdminShopDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminShopDeleteProductActionPerformed(evt);
            }
        });

        jLabel8.setText("Stock:");

        btnAdminShopAddProduct.setText("Save Item");
        btnAdminShopAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminShopAddProductActionPerformed(evt);
            }
        });

        txtAdminProductAddProductStock.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));

        jLabel6.setText("Item Price :");

        jLabel7.setText("Item Name :");

        jLabel3.setText("RM");

        jLabel4.setText("Search:");

        jLabel17.setText("Filter by:");

        jLabel29.setText("Selected item will show in the textfield ");

        jLabel31.setText("Add item will repleace the existing item");

        jLabel32.setText("Add Category:");

        jLabel33.setText("Category:");

        comboAdminProductCategory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminProductCategory1ActionPerformed(evt);
            }
        });

        btnAdminProductAddCategory.setText("Add Category");

        javax.swing.GroupLayout panelProductLayout = new javax.swing.GroupLayout(panelProduct);
        panelProduct.setLayout(panelProductLayout);
        panelProductLayout.setHorizontalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductLayout.createSequentialGroup()
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductLayout.createSequentialGroup()
                                    .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelProductLayout.createSequentialGroup()
                                            .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel33))
                                            .addGap(18, 18, 18)
                                            .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelProductLayout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtAdminProductAddProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                                .addComponent(txtAdminProductAddProductName)
                                                .addComponent(comboAdminProductCategory1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(btnAdminShopAddProduct)
                                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel31)))
                                    .addGap(96, 96, 96))
                                .addGroup(panelProductLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdminShopDeleteProduct)))
                            .addGroup(panelProductLayout.createSequentialGroup()
                                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProductLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboAdminProductCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelProductLayout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(btnAdminProductAddCategory)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(97, 97, 97))))
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdminProductAddProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(comboAdminProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtAdminProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShopPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelProductLayout.setVerticalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductLayout.createSequentialGroup()
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShopPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAdminProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdminProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(panelProductLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(39, 39, 39)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(comboAdminProductCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addComponent(txtAdminProductAddProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAdminProductAddProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAdminProductAddProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminShopAddProduct)
                    .addComponent(btnAdminShopDeleteProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(comboAdminProductCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdminProductAddCategory)
                .addGap(48, 48, 48))
        );

        panel.addTab("Product", panelProduct);

        tablePurchaseHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Order ID", "Total Price", "Delivery Staff", "Order Status"
            }
        ));
        jScrollPane3.setViewportView(tablePurchaseHistory);

        jLabel14.setText("Sort By:");

        btnPurchaseHistoryRefresh.setText("Refresh");
        btnPurchaseHistoryRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseHistoryRefreshActionPerformed(evt);
            }
        });

        jLabel1.setText("Assign Order to Delivery:");

        jLabel10.setText("Order ID:");

        jLabel13.setText("Delivery ID:");

        jLabel34.setText("Date:");

        jLabel35.setText("Order ID:");

        jLabel36.setText("Order Status:");

        txtAdminStatusSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminStatusSearchKeyPressed(evt);
            }
        });

        jLabel37.setText("Search:");

        jLabel38.setText("Delivery Staff:");

        btnAdminStatusAssign.setText("Assign");
        btnAdminStatusAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminStatusAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHistoryLayout = new javax.swing.GroupLayout(panelHistory);
        panelHistory.setLayout(panelHistoryLayout);
        panelHistoryLayout.setHorizontalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(comboAdminStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(comboAdminStatusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAdminStatusStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(45, 45, 45)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(comboAdminStatusDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txtAdminStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAdminStatusAssignOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(45, 45, 45)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHistoryLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(122, 122, 122))
                    .addGroup(panelHistoryLayout.createSequentialGroup()
                        .addComponent(comboAdminStatusAssignDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnAdminStatusAssign)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPurchaseHistoryRefresh)
                .addContainerGap())
        );
        panelHistoryLayout.setVerticalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoryLayout.createSequentialGroup()
                        .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel38)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(comboAdminStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAdminStatusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAdminStatusStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAdminStatusDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoryLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdminStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPurchaseHistoryRefresh)
                    .addGroup(panelHistoryLayout.createSequentialGroup()
                        .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboAdminStatusAssignOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAdminStatusAssignDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdminStatusAssign))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        panel.addTab("Order Status", panelHistory);

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Address", "Postcode", "City", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCart);

        jLabel5.setText("Postcode:");

        label123.setText("Customer Name:");

        btnCartRefreshTable.setText("Refresh");
        btnCartRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartRefreshTableActionPerformed(evt);
            }
        });

        lblCartTotalItem.setText("Address:");

        txtAdminCustomerAddress.setText("jTextField1");

        txtAdminCustomerCity.setText("jTextField1");

        jLabel39.setText("City:");

        jLabel40.setText("State:");

        txtAdminCustomerName.setText("jTextField1");

        txtAdminCustomerState.setText("jTextField2");

        txtAdminCustomerPostcode.setText("jTextField3");

        txtAdminCustomerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminCustomerSearchKeyPressed(evt);
            }
        });

        jLabel41.setText("Search:");

        btnAdminCustomerSave.setText("Save");
        btnAdminCustomerSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCustomerSaveActionPerformed(evt);
            }
        });

        btnAdminCustomerDelete.setText("Delete");
        btnAdminCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCustomerDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCartItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(lblCartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label123)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(lblCartTotalItem)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminCustomerAddress)
                            .addComponent(txtAdminCustomerName)
                            .addComponent(txtAdminCustomerPostcode)
                            .addComponent(txtAdminCustomerCity)
                            .addComponent(txtAdminCustomerState, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnAdminCustomerSave)
                        .addGap(56, 56, 56)
                        .addComponent(btnAdminCustomerDelete)))
                .addGap(5, 5, 5)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(jSeparator1))
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelCustomerLayout.createSequentialGroup()
                                .addComponent(btnCartRefreshTable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAdminCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAdminCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41))
                    .addComponent(btnCartRefreshTable, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label123)
                            .addComponent(txtAdminCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCartTotalItem))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminCustomerPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminCustomerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminCustomerState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(42, 42, 42)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminCustomerSave)
                            .addComponent(btnAdminCustomerDelete))))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCartItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel.addTab("Customer Profile", panelCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCustomerDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCustomerDeleteActionPerformed

    private void btnAdminCustomerSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCustomerSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCustomerSaveActionPerformed

    private void txtAdminCustomerSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminCustomerSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminCustomerSearchKeyPressed

    private void btnCartRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartRefreshTableActionPerformed
        DefaultTableModel objModel = (DefaultTableModel) tableCart.getModel();
        objModel.setRowCount(0);
        ArrayList<String> lines = cFileHandling.readFile("order.txt");
        int count=0;
        for (String eachString: lines)
        {
            Scanner sc = new Scanner(eachString).useDelimiter(";");
            String orderID = sc.next();
            String date = sc.next();
            String time = sc.next();
            String tempUsername = sc.next();
            String tempItemName = sc.next();
            String tempItemPrice = sc.next();
            String tempItemQuantity = sc.next();
            String tempTotalPrice = sc.next();
            String isPaid = sc.next();
            if(tempUsername.equals(username)&&isPaid.equals("unpaid"))
            {
                objModel.addRow(new Object[]{orderID,tempItemName,tempItemPrice,tempItemQuantity,tempTotalPrice});
                count++;
            }
        }
        lblCartTotalItem.setText("Total Items: "+count);
    }//GEN-LAST:event_btnCartRefreshTableActionPerformed

    private void btnAdminStatusAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminStatusAssignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminStatusAssignActionPerformed

    private void txtAdminStatusSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminStatusSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminStatusSearchKeyPressed

    private void btnPurchaseHistoryRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseHistoryRefreshActionPerformed
        ArrayList<String> lines = cFileHandling.readFile("order.txt");
        DefaultTableModel objModel = (DefaultTableModel) tablePurchaseHistory.getModel();
        objModel.setRowCount(0);
        for (String eachString: lines)
        {
            Scanner sc = new Scanner(eachString).useDelimiter(";");
            String orderID = sc.next();
            String date = sc.next();
            String time = sc.next();
            String tempUsername = sc.next();
            String tempItemName = sc.next();
            String tempItemPrice = sc.next();
            String tempItemQuantity = sc.next();
            String tempTotalPrice = sc.next();
            String isPaid = sc.next();
            System.out.println(eachString);
            if(tempUsername.equals(username)&&isPaid.equals("paid"))
            {
                System.out.println(eachString);
                objModel.addRow(new Object[]{date+" "+time,orderID,tempItemName,tempItemPrice,tempItemQuantity,tempTotalPrice});
            }
        }
    }//GEN-LAST:event_btnPurchaseHistoryRefreshActionPerformed

    private void comboAdminProductCategory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminProductCategory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdminProductCategory1ActionPerformed

    private void btnAdminShopAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminShopAddProductActionPerformed

    }//GEN-LAST:event_btnAdminShopAddProductActionPerformed

    private void btnAdminShopDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminShopDeleteProductActionPerformed

    }//GEN-LAST:event_btnAdminShopDeleteProductActionPerformed

    private void txtAdminProductSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminProductSearchKeyPressed
        DefaultTableModel table = (DefaultTableModel) tableAdminProduct.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tableAdminProduct.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtAdminProductSearch.getText().trim()));
    }//GEN-LAST:event_txtAdminProductSearchKeyPressed

    private void comboAdminProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdminProductCategoryActionPerformed

    private void comboAdminRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminRoleActionPerformed

    }//GEN-LAST:event_comboAdminRoleActionPerformed

    private void btnAdminDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDeleteActionPerformed
        int selectedrow = tableAdminUser1.getSelectedRow();

        if (selectedrow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a user to delete!");
        } else {
            if (JOptionPane.showConfirmDialog(null,"Do you sure want to delete this user profile?", "Delete?", JOptionPane.WARNING_MESSAGE) == 0) {
                DefaultTableModel model = (DefaultTableModel) tableAdminUser1.getModel();
                String role = (String) model.getValueAt(selectedrow, 0);
                String username = (String) model.getValueAt(selectedrow, 1);
                model.removeRow(selectedrow);

                File inputFile = new File("userinfo.txt");
                File tempFile = new File("userinfo_temp.txt");

                try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
                    BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        String[] info = line.split(";");
                        String dltRole = info[0].trim();
                        String dltUsername = info[1].trim();

                        if (!(dltUsername.equals(username) && dltRole.equals(role))) {
                            writer.write(line + System.getProperty("line.separator"));
                        }
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(jAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(jAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Delete the original file and rename the temporary file
                if (inputFile.delete()) {
                    tempFile.renameTo(inputFile);
                }
            }
        }
    }//GEN-LAST:event_btnAdminDeleteActionPerformed

    private void btnAdminClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminClearActionPerformed
        txtAdminUsername.setText("");
        txtAdminPassword.setText("");
    }//GEN-LAST:event_btnAdminClearActionPerformed

    private void btnAdminSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSaveActionPerformed
        String Username = txtAdminUsername.getText();
        String Password = txtAdminPassword.getText();
        String ConPassword = txtAdminPassword2.getText();
        String Role = (String)comboAdminRole.getSelectedItem();
        // Create a cAdmin object
        cAdmin admin = new cAdmin();

        boolean usernameExists = admin.saveUserInfo(Role, Username, Password);

        if (!ConPassword.equals(Password)) {
            JOptionPane.showConfirmDialog(null,"Password Incorrect!",
                "Please re-enter password", JOptionPane.ERROR_MESSAGE);
            txtAdminPassword.setText("");
            txtAdminPassword2.setText("");
        }
        
        else if (Password.equals("") || Username.equals("")) {
                JOptionPane.showConfirmDialog(null,"Kindly fill in all the blank field",
                    "No empty field allowed", JOptionPane.WARNING_MESSAGE);
            }
        
        else {
            if (usernameExists) {
                JOptionPane.showConfirmDialog(null,"The username have been taken, Please contact Administator for more information",
                        "User Exsisted", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showConfirmDialog(null,"User added!",
                        "User Exsisted", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_btnAdminSaveActionPerformed

    private void txtAdminSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminSearchKeyPressed

        // if txtShopSearch is keyed in with some value, then the table will updated based on the value
        DefaultTableModel table = (DefaultTableModel) tableAdminUser1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);

        // show the filtered data in table
        tableAdminUser1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtAdminSearch.getText().trim()));
    }//GEN-LAST:event_txtAdminSearchKeyPressed

    private void comboAdminSearchRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminSearchRoleActionPerformed

    }//GEN-LAST:event_comboAdminSearchRoleActionPerformed

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jDashboard().setVisible(true);
            }
        }); 

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminClear;
    private javax.swing.JButton btnAdminCustomerDelete;
    private javax.swing.JButton btnAdminCustomerSave;
    private javax.swing.JButton btnAdminDelete;
    private javax.swing.JButton btnAdminProductAddCategory;
    private javax.swing.JButton btnAdminSave;
    private javax.swing.JButton btnAdminShopAddProduct;
    private javax.swing.JButton btnAdminShopDeleteProduct;
    private javax.swing.JButton btnAdminStatusAssign;
    private javax.swing.JButton btnCartRefreshTable;
    private javax.swing.JButton btnPurchaseHistoryRefresh;
    private javax.swing.JComboBox<String> comboAdminProductCategory;
    private javax.swing.JComboBox<String> comboAdminProductCategory1;
    private javax.swing.JTextField comboAdminProductCategory2;
    private javax.swing.JComboBox<String> comboAdminRole;
    private javax.swing.JComboBox<String> comboAdminSearchRole;
    private javax.swing.JComboBox<String> comboAdminStatusAssignDelivery;
    private javax.swing.JComboBox<String> comboAdminStatusAssignOrder;
    private javax.swing.JComboBox<String> comboAdminStatusDate;
    private javax.swing.JComboBox<String> comboAdminStatusDelivery;
    private javax.swing.JComboBox<String> comboAdminStatusID;
    private javax.swing.JComboBox<String> comboAdminStatusStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label123;
    private javax.swing.JLabel lblCartItemName;
    private javax.swing.JLabel lblCartPrice;
    private javax.swing.JLabel lblCartTotalItem;
    private javax.swing.JLabel lblShopPrice;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JPanel panelProduct;
    private javax.swing.JPanel panelRole;
    private javax.swing.JTable tableAdminProduct;
    private javax.swing.JTable tableAdminUser1;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tablePurchaseHistory;
    private javax.swing.JTextField txtAdminCustomerAddress;
    private javax.swing.JTextField txtAdminCustomerCity;
    private javax.swing.JTextField txtAdminCustomerName;
    private javax.swing.JTextField txtAdminCustomerPostcode;
    private javax.swing.JTextField txtAdminCustomerSearch;
    private javax.swing.JTextField txtAdminCustomerState;
    private javax.swing.JPasswordField txtAdminPassword;
    private javax.swing.JPasswordField txtAdminPassword2;
    private javax.swing.JTextField txtAdminProductAddProductName;
    private javax.swing.JTextField txtAdminProductAddProductPrice;
    private javax.swing.JSpinner txtAdminProductAddProductStock;
    private javax.swing.JTextField txtAdminProductSearch;
    private javax.swing.JTextField txtAdminSearch;
    private javax.swing.JTextField txtAdminStatusSearch;
    private javax.swing.JTextField txtAdminUsername;
    // End of variables declaration//GEN-END:variables
}
